[openelec] implement DEVICE-Tree into OpenELEC build-tree   * Refactor Odroid's for DEVICE-Tree

diff --git a/config/path b/config/path
--- a/config/path
+++ b/config/path
@@ -1,3 +1,4 @@
+#!/bin/bash
 set -e
 
 . config/functions
@@ -19,7 +20,11 @@ set -e
 HOST_NAME=`$LOCAL_CC -dumpmachine`
 TARGET_NAME=$(echo $TARGET_SUBARCH | sed -e "s,-,,")-openelec-linux-gnu${TARGET_ABI}
 
-BUILD=$BUILD_BASE.$DISTRONAME-$PROJECT.$TARGET_ARCH-$OPENELEC_VERSION
+if [ -n "$DEVICE" ]; then
+  BUILD=$BUILD_BASE.$DISTRONAME-$PROJECT.$DEVICE.$TARGET_ARCH-$OPENELEC_VERSION
+else
+  BUILD=$BUILD_BASE.$DISTRONAME-$PROJECT.$TARGET_ARCH-$OPENELEC_VERSION
+fi
 TARGET_IMG=$ROOT/$TARGET
 TARGET_ADDONS="$TARGET_IMG/$ADDONS/$ADDON_PATH"
 ADDON_BUILD="$BUILD/$ADDONS/$1"
@@ -69,7 +74,24 @@ SED="sed -i"
     _FOUND=0
     PKG_DIR=""
 
-    # first check project folder for a package
+    # first check project device folder for a package
+    for DIR in $(find $ROOT/projects/$PROJECT/devices/$DEVICE/packages -type d -name $_PKG_ROOT_NAME 2>/dev/null); do
+      if [ -r "$DIR/package.mk" ]; then
+        # found first, set $PKG_DIR
+        PKG_DIR="$DIR"
+        # keep track of dirs with package.mk for detecting multiple folders
+        _ALL_DIRS="${_ALL_DIRS}${DIR}\\n"
+        _FOUND=$((_FOUND+1))
+        if [ $_FOUND -gt 1 ]; then
+          # _FOUND more ? fail
+          echo "Error - multiple package folders:"
+          echo -e "$_ALL_DIRS"
+          exit 1
+        fi
+      fi
+    done
+
+    # next check project folder for a package
     for DIR in $(find $ROOT/projects/$PROJECT/packages -type d -name $_PKG_ROOT_NAME 2>/dev/null); do
       if [ -r "$DIR/package.mk" ]; then
         # found first, set $PKG_DIR
diff --git a/scripts/mkimage-odroid b/scripts/mkimage-odroid
--- a/scripts/mkimage-odroid
+++ b/scripts/mkimage-odroid
@@ -1,4 +1,5 @@
 #!/bin/bash
+
 ################################################################################
 #      This file is part of OpenELEC - http://www.openelec.tv
 #      Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
@@ -72,7 +73,7 @@ trap cleanup SIGINT
 # create an image
   echo "image: creating image: $DISK..."
   echo "  dd if=/dev/zero of=$DISK bs=512 count=$(Sector $(MiB $DISK_SIZE))"
-  dd if=/dev/zero of=$DISK bs=512 count=$(Sector $(MiB $DISK_SIZE)) $DEBUG_NULL > /dev/null 2>&1 || error "Create image failed!"
+  dd if=/dev/zero of=$DISK bs=512 count=$(Sector $(MiB $DISK_SIZE)) > /dev/null 2>&1 || error "Create image failed!"
   sync
 
 # write a disklabel
@@ -107,6 +108,8 @@ trap cleanup SIGINT
   losetup -o $(($SYSTEM_PART_START * 512 )) --sizelimit $(MiB $SYSTEM_SIZE) "$LOOP" "$DISK" || error "Setup partition 1 loop failed!"
   echo "  mkfs.vfat -c -F 32 -n System \"$LOOP\""
   mkfs.vfat -c -F 32 -n System "$LOOP" > /dev/null 2>&1 || error "Create FS on partition 1 failed!"
+  echo "  fsck -a \"$LOOP\""
+  fsck -a "$LOOP" > /dev/null 2>&1 || error "Partition 1 FS check failed!"
   sync
 
 # mount partition 1
@@ -116,20 +119,25 @@ trap cleanup SIGINT
 
   # copy files
   echo "image: copying files to partition 1..."
-  echo "  XU3/KERNEL"
-  install -D -m 0644 $BUILD/$(basename $(ls -d $BUILD/linux-odroid-xu3-*))/arch/arm/boot/zImage $OE_TMP/XU3/KERNEL
-  echo "  U2/KERNEL"
-  install -D -m 0644 $BUILD/$(basename $(ls -d $BUILD/linux-odroid-u2-*))/arch/arm/boot/zImage $OE_TMP/U2/KERNEL
+  echo "  KERNEL"
+  if [ "$DEVICE" = "C1" ]; then
+    install -D $INSTALL/../KERNEL "$OE_TMP/KERNEL"
+    ( cd $RELEASE_DIR ;  md5sum -t target/KERNEL > target/KERNEL.md5; )
+  else
+    install -D $RELEASE_DIR/target/KERNEL "$OE_TMP/KERNEL"
+  fi
   echo "  SYSTEM"
-  install -D $INSTALL/../SYSTEM "$OE_TMP/SYSTEM"
+  install -D $RELEASE_DIR/target/SYSTEM "$OE_TMP/SYSTEM"
   echo "  INITRD"
-  install -D $INSTALL/../uInitrd "$OE_TMP/INITRD"
-  echo "  XU3/DTB"
-  install -D $INSTALL/usr/share/bootloader/XU3/DTB "$OE_TMP/XU3/DTB"
-  echo "  XU3/BOOT.SCR"
-  install -D $INSTALL/usr/share/bootloader/XU3/boot-$DEFAULT_SCR.scr "$OE_TMP/XU3/BOOT.SCR"
-  echo "  U2/BOOT.SCR"
-  install -D $INSTALL/usr/share/bootloader/U2/boot-$DEFAULT_SCR.scr "$OE_TMP/U2/BOOT.SCR"
+  install -D $RELEASE_DIR/target/INITRD "$OE_TMP/INITRD"
+  for f in $(ls $RELEASE_DIR/3rdparty/bootloader/boot.* 2>/dev/null); do
+    echo "  $(basename $f)"
+    install -D $f "$OE_TMP/$(basename $f)"
+  done
+  for f in $(ls $RELEASE_DIR/3rdparty/bootloader/*.dtb 2>/dev/null); do
+    echo "  $(basename $f)"
+    install -D $f "$OE_TMP/$(basename $f)"
+  done
 
 # unmount partition 1
   echo "image: unmounting partition 1..."
@@ -161,7 +169,7 @@ trap cleanup SIGINT
     sync
   fi
 
-# unmount partition 2 
+# unmount partition 2
   echo "image: unmounting partition 2..."
   echo "  umount \"$LOOP\""
   umount "$LOOP"
@@ -170,8 +178,8 @@ trap cleanup SIGINT
 # cleanup
   cleanup
 
-# create u2/3 and xu3 images
-#  $ROOT/tools/mkimg/mkimg
+# fuse image
+  $ROOT/tools/mkfuse/mkfuse $DEVICE $DISK
 
-# make self-fusing binary
-  $ROOT/tools/mkbin/mkbin
+# compress image
+  gzip $DISK
